name: Scrape Theatres

on:
  schedule:
    - cron: "0 13 * * 3"
    - cron: "0 13 * * 4"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # Instala as dependências do Chrome
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev

      - name: Run Wednesday script
        if: github.event.schedule == '0 13 * * 3'
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: pnpm run wednesday

      - name: Run Thursday script
        if: github.event.schedule == '0 13 * * 4'
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: pnpm run thursday
